### ISSUE TITLE
Unable to build powergate CLI

### ISSUE THREAD

**Issue by chaitanyaprem** [textileio/powergate#882]
Followed the steps mentioned in https://docs.textile.io/powergate/ to clone and build Powergate CLI. 
I am facing following errors and unable to proceed. 

My environment is M1 macbook Pro with golang version `go version go1.18 darwin/amd64`

On running `make install-pow` following error is displayed. 
```
go: downloading github.com/marten-seemann/qtls-go1-17 v0.1.0-rc.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.21.2/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration
make: *** [install-pow] Error 2
```

Thought i found a workaround mentioned here https://github.com/ipfs/go-ipfs/issues/8819 . 
Tried to proceed with it but I am running into the below error. Looks like go-ipfs version used is 0.8 which is very old and using some flags which have been removed in later dependency (quic-go).
```
CGO_ENABLED=0 go install -ldflags="-X github.com/textileio/powergate/v2/buildinfo.GitSummary=v2.6.2-6-gb82b011-dirty -X github.com/textileio/powergate/v2/buildinfo.Version=git -X github.com/textileio/powergate/v2/buildinfo.BuildDate=2022-05-12T00:08:11Z -X github.com/textileio/powergate/v2/buildinfo.GitCommit=b82b011 -X github.com/textileio/powergate/v2/buildinfo.GitBranch=master -X github.com/textileio/powergate/v2/buildinfo.GitState=dirty" ./cmd/pow
# github.com/ipfs/go-ipfs/core/node/libp2p
../../../go/pkg/mod/github.com/ipfs/go-ipfs@v0.8.0/core/node/libp2p/transport.go:21:7: undefined: quic.RetireBugBackwardsCompatibilityMode
make: *** [install-pow] Error 2
```

**Comment by jsign** [comment]
The newest libp2p has a limitation (I guess is temporal) for people compiling with Go v1.18.x, which is a release from some weeks ago.

You need to compile with v1.17.x or older. (i.e: I tried with v1.17.8 now and didn't have an issue compiling)
Be sure that your git repo is clean (no changes).

**Comment by chaitanyaprem** [comment]
Thanks, will try on a 1.17 version then.

But, is it the lipp2p which is causing the issue? Because i don't see an open issue for the same under libp2p. 
And the issue i have referenced above seems to have addressed this in go-ipfs and libp2p. 
I see that go-ipfs-0.8 is mentioned as dependency in powergate which is an older version and hence must be having this limitation whereas the latest is 0.12.

**Comment by jsign** [comment]
Yes, it's libp2p since the error:
> ../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.21.2/internal/qtls/go118.go:5:13: cannot use "quic-go doesn't build on Go 1.18 yet." (untyped string constant) as int value in variable declaration

Comes from libp2p.

Correct, this repo isn't using the latest version of libp2p.

**Comment by jsolly** [comment]
I ran into this error and initially logged the issue in the [wrong repo](https://github.com/filecoin-project/filecoin-docs/issues/1355).

After installing Go 1.17.13 the error went away.

**Comment by jsolly** [comment]
@jsign I forked this repo and added a note to the repo's home page about the Go versions that are supported in https://github.com/jsolly/powergate/commit/bda20f6bbd0e55d23dcd41ac2e6ab9b14d5a6584

I noticed I on the [PR page](https://github.com/textileio/powergate/compare) that it didn't have the option to choose my fork for a PR. What's the process for a contributor to open a PR?

I checked the [Contributor doc](https://github.com/textileio/powergate/blob/master/CONTRIBUTING.md) and it is empty.

**Comment by jsign** [comment]
> @jsign I forked this repo and added a note to the repo's home page about the Go versions that are supported in [jsolly@bda20f6](https://github.com/jsolly/powergate/commit/bda20f6bbd0e55d23dcd41ac2e6ab9b14d5a6584)
> 
> I noticed I on the [PR page](https://github.com/textileio/powergate/compare) that it didn't have the option to choose my fork for a PR. What's the process for a contributor to open a PR?
> 
> I checked the [Contributor doc](https://github.com/textileio/powergate/blob/master/CONTRIBUTING.md) and it is empty.

There isn't a special process to create a PR, you should be able to created by clicking the "open pull request" button in your fokred repo:
![image](https://user-images.githubusercontent.com/6136245/186154670-74eb98fb-0d97-4d58-be20-06b9306c871f.png)

BTW, thanks for the contribution.

**Comment by jsolly** [comment]
Thanks! I opened a new PR to update the home page with information about installing Go.
https://github.com/textileio/powergate/pull/893

**Comment by jsign** [comment]
Closed by #893
